import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TanstackProviders from "../../providers/TanstackProviders";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TanstackProviders>
        <body className={inter.className}>
          <ToastContainer />
          <Header />

          {children}
        </body>
      </TanstackProviders>
    </html>
  );
}
