import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProviders from "../../providers/TanstackProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TanstackProviders>
        <body className={inter.className}>{children}</body>
      </TanstackProviders>
    </html>
  );
}
